baseURL: "https://salatielaizza.com/"
languageCode: "en-us"
title: "Salatiel Aizza"
defaultContentLanguage: "en"
enableRobotsTXT: true
theme: "PaperMod"

outputs:
  home:
    - HTML
    - RSS
    - JSON

menu:
  main:
    - name: "Posts"
      url: "/posts/"
      weight: 1
    - name: "Tags"
      url: "/tags/"
      weight: 2
    - identifier: "github"
      url: "https://github.com"
      weight: 3
      pre: "<span data-feather='github'></span>"
      post: ""

params:
  disableSearch: false
  search:
    enabled: true         # <- imprescindible
    # shortcut: "/"       # opcional
    # fuse: true          # (PaperMod usa Fuse.js por defecto)

  disableThemeToggle: false
  defaultTheme: auto
  homeInfoParams:
    Title: "Salatiel Aizza - Blog"
    Content: "I am a Linux system administrator and I like to automate processes. In this blog, I will share what I learn about Kubernetes, Linux, and other DevOps technologies."
  socialIcons:
    - name: "github"
      url: "https://github.com/salatielaizza"
    - name: "linkedin"
      url: "https://www.linkedin.com/in/salatielaizza/?locale=en_US"

  # ⚙️ Opciones de Fuse.js
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 1   # <- nombre correcto
    keys: ["title", "permalink", "summary", "content"]

  ShowCodeCopyButtons: true
  ShowShareButtons: true
  ShowReadingTime: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowToc: true

  cover:
    responsiveImages: false
    linkFullImages: true
    hidden: false
    hiddenInList: false
    hiddenInSingle: false
module:
  imports:
    - path: github.com/adityatelange/hugo-PaperMod

# (Opcional pero recomendado) quita la clave `theme:` o déjala vacía
# theme: ""

